In [13]:
!pip install torch --user
import numpy as np
import torch
from scipy.special import softmax

In [65]:
A = np.array([0,2,np.sqrt(2),2,2,0,np.sqrt(2),2*np.sqrt(2),np.sqrt(2),np.sqrt(2),0,np.sqrt(2),2,2*np.sqrt(2),np.sqrt(2),0])
A = A.reshape((4,4))
F = np.array([[0,1],[0,1],[1,0],[1,0]])
D_ = np.diag(1/np.sum(A, axis=1))
Q = D_@A@F

In [66]:
print(Q.T@Q)
softmax(np.sum(Q.T@Q, axis=0))

[[1.0219778  0.84812115]
 [0.84812115 1.2817799 ]]


array([0.43541236, 0.56458764])

In [46]:
A = np.array([0,2,np.sqrt(2),2,np.sqrt(2),np.sqrt(2),0,np.sqrt(2)])
A = A.reshape((4,2))
F = np.array([[0,1],[1,0]])
D_ = np.diag(1/np.sum(A, axis=1))
# print(D_1.shape, A.shape, D_2.shape, F.shape)
Q = D_@A@F

In [48]:
print(Q.T@Q)
softmax(np.sum(Q.T@Q, axis=0))

[[2.59314575 0.49264069]
 [0.49264069 0.42157288]]


array([0.89766754, 0.10233246])

In [61]:
A = np.array([0,2,np.sqrt(2),2,2,2*np.sqrt(2),np.sqrt(2),0])
A = A.reshape((4,2))
F = np.array([[0,1],[1,0]])
D_ = np.diag(1/np.sum(A, axis=1))
# print(D_1.shape, A.shape, D_2.shape, F.shape)
Q = D_@A@F

In [62]:
print(Q.T@Q)
softmax(np.sum(Q.T@Q, axis=0))

[[1.6862915  0.48528137]
 [0.48528137 1.34314575]]


array([0.58495446, 0.41504554])

In [63]:
A = np.array([0,2,np.sqrt(2),2*np.sqrt(2),2,0,np.sqrt(2),2,np.sqrt(2),np.sqrt(2),0,np.sqrt(2),2*np.sqrt(2),2,np.sqrt(2),0])
A = A.reshape((4,4))
F = np.array([[0,1],[0,1],[1,0],[1,0]])
D_ = np.diag(1/np.sum(A, axis=1))
Q = D_@A@F

In [69]:
print(Q.T@Q)
softmax(Q.T@Q)

[[1.0219778  0.84812115]
 [0.84812115 1.2817799 ]]


array([[0.25141369, 0.21129243],
       [0.21129243, 0.32600145]])

In [67]:
A = np.array([0,2,np.sqrt(2),2,2,0,np.sqrt(2),2*np.sqrt(2),np.sqrt(2),np.sqrt(2),0,np.sqrt(2),2,2*np.sqrt(2),np.sqrt(2),0])
A = A.reshape((4,4))
F = np.array([[0,1],[1,0],[1,0],[0,1]])
D_ = np.diag(1/np.sum(A, axis=1))
Q = D_@A@F

In [68]:
print(Q.T@Q)
softmax(np.sum(Q.T@Q, axis=0))

[[1.0219778  0.84812115]
 [0.84812115 1.2817799 ]]


array([0.43541236, 0.56458764])

In [71]:
A = np.array([0,2,np.sqrt(2),2,2*np.sqrt(2),2,0,np.sqrt(2),2,2*np.sqrt(2),np.sqrt(2),np.sqrt(2),0,np.sqrt(2),np.sqrt(2),2*np.sqrt(2),2,np.sqrt(2),0,2,2,2*np.sqrt(2),np.sqrt(2),2,0])
A = A.reshape((5,5))
F = np.array([[0,1,0],[0,1,0],[1,0,0],[0,0,1],[1,0,0]])
D_ = np.diag(1/np.sum(A, axis=1))
Q = D_@A@F

In [72]:
print(Q.T@Q)
softmax(np.sum(Q.T@Q, axis=0))

[[0.70001827 0.69354249 0.37115787]
 [0.69354249 1.05404051 0.40927125]
 [0.37115787 0.40927125 0.29799801]]


array([0.33516804, 0.4960951 , 0.16873687])